# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c32669a3754647b7f7374e9ea032af1db8e02ed1c93ebfc63e630c4ac477d6818bbdc31198d35a00ab52149ddece1070900b1236d9b530b325d5ab409d857c99

test:
  secret_key_base: 57af39eb518cabfbd28ac4cd36c47c30dfcb593b364a4311f867d46e1832b8ea704cf8de18cb8ea5a0a80f271a8f9c34e579a068ee0e08453a44b5b231ae863e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
